import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getCourses } from "../utils/db";

export default function Home({ courses }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Courses</h1>
        <pre>{JSON.stringify(courses, null, 2)}</pre>
      </main>

      {/* <footer className={styles.footer}>
        
      </footer> */}
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await getCourses();

  return {
    props: {
      courses: JSON.parse(JSON.stringify(data)), // this will be passed to our Component as a prop
    },
  };
};
